CONTIKI_PROJECT = sleepy-cusum
all: $(CONTIKI_PROJECT) 

APPS = serial-shell collect-view sleepy-cusum-node global-sensor tool-sample-stats
CONTIKI=/home/user/contiki

include $(CONTIKI)/Makefile.include
