CONTIKI_PROJECT = gaussian-cusum
all: $(CONTIKI_PROJECT) 

APPS = serial-shell powertrace collect-view cusum-seq global-sensor tool-sample-stats
CONTIKI=/home/user/contiki

include $(CONTIKI)/Makefile.include
