CONTIKI_PROJECT = temperature
all: $(CONTIKI_PROJECT) 

APPS = serial-shell powertrace collect-view global-sensor tool-sample-stats test-change-detect
CONTIKI=/home/user/contiki

include $(CONTIKI)/Makefile.include
