CONTIKI_PROJECT = adaptive-cusum
all: $(CONTIKI_PROJECT)

APPS = serial-shell collect-view de-adaptive-cusum global-sensor tool-sample-stats
CONTIKI=/home/user/contiki

include $(CONTIKI)/Makefile.include
